/// This file is generated by kopgen. Do not edit manually. If you need to make adjustments add it to .openapi-generator-ignore file.
use anyhow::Context;
use std::process::Stdio;
use tokio::process::Command;

#[derive(Default)]
pub struct Operator {}

impl Operator {
    pub fn new() -> Self {
        Self::default()
    }

    pub async fn package(&self, container_registry: &str) -> anyhow::Result<()> {
        Command::new("docker")
            .args([
                "build",
                "-t",
                &format!("{}/operator:latest", container_registry),
                "-f",
                "../Dockerfile",
                "..",
            ])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `docker build`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`docker build` failed"))?;

        Command::new("docker")
            .args(["push", &format!("{}/operator:latest", container_registry)])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `docker push`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`docker push` failed"))?;

        Ok(())
    }

    pub async fn deploy_on(&self, cluster_name: &str) -> anyhow::Result<()> {
        Command::new("kubectl")
            .args(["config", "use-context", cluster_name])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `kubectl config use-context`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`kubectl config use-context` failed"))?;

        Command::new("kubectl")
            .args(["apply", "-f", "../manifests/rbac/"])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `kubectl apply`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`kubectl apply` failed"))?;

        Command::new("kubectl")
            .args(["apply", "-f", "../manifests/operator/"])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `kubectl apply`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`kubectl apply` failed"))?;

        Command::new("kubectl")
            .args(["rollout", "status", "deployment/operator", "--timeout=60s"])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `kubectl rollout status` for operator")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`kubectl rollout status` for operator failed"))?;

        Ok(())
    }

    pub async fn undeploy_from(&self, cluster_name: &str) -> anyhow::Result<()> {
        Command::new("kubectl")
            .args(["config", "use-context", cluster_name])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `kubectl config use-context`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`kubectl config use-context` failed"))?;

        Command::new("kubectl")
            .args(["delete", "-f", "../manifests/operator/"])
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await
            .context("Failed to execute `kubectl delete`")?
            .success()
            .then_some(())
            .ok_or_else(|| anyhow::anyhow!("`kubectl delete` failed"))?;

        Ok(())
    }
}
