/// This file is generated by kopgen. Do not edit manually. If you need to make adjustments add it to .openapi-generator-ignore file.
use kube::CustomResourceExt;

fn main() {
    let crds = vec![
        
    ];

    let generated_hint = "# This file is generated by k8s-crdgen crate. Do not edit manually. If you need to make adjustments add it to .openapi-generator-ignore file or edit its template.";
    for crd in crds {
        match serde_yaml::to_string(&crd) {
            Ok(yaml) => print!("{}\n\n---\n{}", generated_hint, yaml),
            Err(e) => eprintln!("Error serializing CRD to YAML: {}", e),
        }
    }
}
